import type { GameState } from './state';
import { playerBusinesses, playerCompany } from './state';
import { clamp, sum } from './util';
import { businessType } from '../data/businessTypes';
import type { DistrictId } from './types';
import { pushAlert } from './alerts';

export interface WorldStory { id:string; day:number; title:string; detail:string; category:'COMPANY'|'MARKET'|'PEOPLE'|'CITY'|'COMPETITION'|'CRISIS'; importance:number; }
export interface WorldDecision { day:number; title:string; detail:string; }
export interface CompanyRecord { name:string; value:number; day:number; }
export interface Living3State {
 version:1; stories:WorldStory[]; decisions:WorldDecision[]; records:{revenue:CompanyRecord; profit:CompanyRecord; customers:CompanyRecord; businesses:CompanyRecord; employees:CompanyRecord}; lastRevenue:number; lastProfit:number; lastCustomers:number; lastStoryDay:number;
}
const MAX=100;
function create():Living3State{return{version:1,stories:[],decisions:[],records:{revenue:{name:'',value:0,day:0},profit:{name:'',value:0,day:0},customers:{name:'',value:0,day:0},businesses:{name:'',value:0,day:0},employees:{name:'',value:0,day:0}},lastRevenue:0,lastProfit:0,lastCustomers:0,lastStoryDay:0};}
export function living3State(state:GameState):Living3State{const holder=state as GameState&{living3?:Living3State};if(!holder.living3)holder.living3=create();return holder.living3;}
function story(state:GameState,category:WorldStory['category'],title:string,detail:string,importance=1):void{const d=living3State(state);d.stories.unshift({id:`story-${state.day}-${state.hour}-${Math.random().toString(36).slice(2,7)}`,day:state.day,title,detail,category,importance});d.stories=d.stories.slice(0,MAX);}
function playerMetrics(state:GameState){const businesses=playerBusinesses(state).filter(b=>b.status==='open');const employees=state.employees.filter(e=>e.companyId===state.playerCompanyId);const revenue=sum(businesses,b=>b.today.revenue);const profit=sum(businesses,b=>b.today.revenue-b.today.cogs-b.today.wages-b.today.rent-b.today.marketing-b.today.otherCosts);const customers=sum(businesses,b=>b.today.customers);return{businesses,employees,revenue,profit,customers};}
function records(state:GameState):void{const d=living3State(state);const m=playerMetrics(state);const company=playerCompany(state);const checks:[keyof Living3State['records'],number,string][]=[['revenue',m.revenue,`Daily revenue record`],['profit',m.profit,`Daily profit record`],['customers',m.customers,`Daily customer record`],['businesses',m.businesses.length,`Largest operating portfolio`],['employees',m.employees.length,`Largest workforce`]];for(const[key,value,label]of checks){if(value>(d.records[key].value||0)){d.records[key]={name:company.name,value,day:state.day};if(value>0&&state.day>1)story(state,'COMPANY',label,`${company.name} reached a new record on day ${state.day}.`,2);}}}
function detect(state:GameState):void{const d=living3State(state);const m=playerMetrics(state);if(d.lastStoryDay===state.day)return;const revDelta=d.lastRevenue?((m.revenue-d.lastRevenue)/Math.max(1,d.lastRevenue)):0;const profitDelta=d.lastProfit?m.profit-d.lastProfit:0;if(revDelta>=.15)story(state,'COMPANY','A strong trading day',`Revenue jumped ${Math.round(revDelta*100)}% versus the previous settlement. Demand or execution is working in your favour.`,2);if(revDelta<=-.2&&d.lastRevenue>100)story(state,'CRISIS','Revenue is under pressure',`Revenue fell ${Math.round(Math.abs(revDelta)*100)}%. Check demand, prices, stockouts and competitors before the weakness compounds.`,3);if(profitDelta>0&&m.profit>0)story(state,'COMPANY','Profitability is improving',`Today's operating profit is €${Math.round(m.profit).toLocaleString('en-GB')}.`,1);const stressed=m.employees.filter(e=>e.stress>=75);if(stressed.length)story(state,'PEOPLE','People are feeling the pressure',`${stressed.length} employee${stressed.length===1?' is':'s are'} at high stress. Persistent pressure can reduce productivity and retention.`,3);const weak=m.businesses.find(b=>b.reviewScore<3&&b.reviewCount>5);if(weak)story(state,'COMPANY','A reputation problem is emerging',`${weak.name} has slipped below 3★. Reviews may begin hurting repeat demand.`,3);d.lastRevenue=m.revenue;d.lastProfit=m.profit;d.lastCustomers=m.customers;d.lastStoryDay=state.day;}
function cityPulse(state:GameState):void{if(state.day%14!==0)return;let best:{id:DistrictId;score:number}|null=null;for(const id of Object.keys(state.districts) as DistrictId[]){const score=state.districts[id].demandIndex*state.districts[id].propertyIndex;if(!best||score>best.score)best={id,score};}if(best)story(state,'CITY','A district is pulling ahead',`${best.id} currently has the strongest combined demand and property momentum. It may be worth watching for expansion.`,2);}
export function addWorldDecision(state:GameState,title:string,detail:string):void{const d=living3State(state);d.decisions.unshift({day:state.day,title,detail});d.decisions=d.decisions.slice(0,50);}
export function settleLiving3(state:GameState):void{detect(state);records(state);cityPulse(state);const company=playerCompany(state);if(company.cash<5000&&company.cash>=0&&state.day%3===0)pushAlert(state,'warning','Living world: liquidity risk',`The company has only €${Math.round(company.cash).toLocaleString('en-GB')} cash. Recent operating conditions suggest protecting liquidity.`,null);}
export function getStories(state:GameState):WorldStory[]{return living3State(state).stories;}
export function getWorldDecisions(state:GameState):WorldDecision[]{return living3State(state).decisions;}
export function getRecords(state:GameState){return living3State(state).records;}
export function explainMetric(state:GameState,metric:'revenue'|'profit'|'customers'):string[]{const m=playerMetrics(state);const out:string[]=[];for(const b of m.businesses){const type=businessType(b.typeId);if(!type)continue;const utilization=b.today.customers/Math.max(1,type.baseCustomers);if(utilization<.6)out.push(`${b.name}: demand/utilisation is below potential.`);if(b.today.lostCustomers>0)out.push(`${b.name}: ${b.today.lostCustomers} customers were lost, indicating capacity or stock pressure.`);if(b.serviceQuality<60)out.push(`${b.name}: service quality is limiting conversion or repeat business.`);}if(state.economy.confidence<90)out.push('Consumer confidence is below the starting level, reducing discretionary demand.');if(state.economy.growth<0)out.push('The economy is contracting, which can soften demand.');if(!out.length)out.push('No dominant negative driver is detected in the latest operating data.');return out.slice(0,5);}
